### ISSUE TITLE
The perplexity become larger after some epochs, but still training

### ISSUE THREAD

**Issue by jamesweb1** [isi-nlp/Zoph_RNN#2]
I try to train my model by sequence to sequence way. I find the program work well before 30 epochs, and it become convergent in 30th epoch to get the minimum perplexity (about 4.99). But the program is still training after that and get the worse perplexity because I set the number of epochs to 80. I'm afraid of getting the worst result in the end of program. So I wish I could get the model in the 30th epoch and stop it. How can I solve this issue?

**Comment by BarretZoph** [comment]
Use the -B flag. This will save the best model.

**Comment by cocaer** [comment]
@jamesweb1  how do u kown the  perplexity after each epoch? Which flag did u use?
